version: 2
updates:
  # Enable version updates for pipenv
  - package-ecosystem: "pip"
    # Look for "Pipfile" and "Pipfile.lock" files in the "root" directory
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "weekly"
      day: "saturday"
    # Raise all pipenv pull requests with a reviewer      
    reviewers:
      - "miguel-osuna"
    # Raise all pipenv pull requests with an assignee
    assignees:
      - "miguel-osuna"
    # Raise all pipenv pull requests with custom labels
    labels:
      - "chore"

  # Enable version updates for docker images
  - package-ecosystem: "docker"
    # Look for "Dockerfile" in the "root" directory
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "weekly"
      day: "saturday"
    # Raise all pipenv pull requests with an assignee
    assignees:
      - "miguel-osuna"
    # Raise all pipenv pull requests with custom labels
    labels:
      - "chore"
