version: "3"

services:
  application:
    build:
      context: .
      dockerfile: ./docker/local/application/Dockerfile
    image: famous_quotes_bot_local
    container_name: famous_quotes_bot
    volumes:
      - .:/app
    env_file:
      - ./.envs/.local/.application
    ports:
      - "5000:5000"
    command: /start
